version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: dgc-issuance-service-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dgc
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=dgc_adm
      - MYSQL_PASSWORD=admin
    networks:
      persistence:

  backend:
    build: .
    image: eu-digital-green-certificates/dgc-issuance-service
    container_name: dgc-issuance-service
    volumes:
      - ./certs:/ec/prod/app/san/dgc
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://dgc-issuance-service-mysql:3306/dgc
      - SPRING_DATASOURCE_USERNAME=dgc_adm
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      backend:
      persistence:
    restart: unless-stopped

networks:
  backend:
  persistence:
