server:
  port: 8080
spring:
  profiles:
    group:
      dev: h2
  application:
    name: eu-digital-green-certificates-issuence
  datasource:
    jndi-name: false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
    change-log: classpath:db/changelog.xml
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
  server:
    port: -1
issuance:
  dgciPrefix: "dgci:V1:DE"
  keyStoreFile: test_certs/cert_devtest_keystore.jks
  keyStorePassword: dgca
  certAlias: edgc_dev_test
  privateKeyPassword: dgca
  countryCode: DE
dgc:
  trustAnchor:
    keyStorePath: /ec/prod/app/san/dgc/dgc-ta.jks
    keyStorePass: dgc-p4ssw0rd
    certificateAlias: dgc_trust_anchor
  cert-auth:
    header-fields:
      thumbprint: X-SSL-Client-SHA256
      distinguished-name: X-SSL-Client-DN
springdoc:
  api-docs:
    enabled: false
