spring:
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
dgc:
  trustAnchor:
    keyStorePath: classpath:keystore/dgc-ta.jks
