server:
  port: 8080
spring:
  application:
    name: dgca-issuance-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
    change-log: classpath:db/changelog.xml
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
issuance:
  dgciPrefix: "dgci:V1:DE"
  keyStoreFile: test_certs/cert_devtest_keystore.jks
  keyStorePassword: dgca
  certAlias: edgc_dev_ec
  privateKeyPassword: dgca
  countryCode: DE
dgc:
  trustAnchor:
    keyStorePath: classpath:keystore/dgc-ta.jks
#dgc:
#  trustAnchor:
#    keyStorePath: /ec/prod/app/san/dgc/dgc-ta.jks
    keyStorePass: dgc-p4ssw0rd
    certificateAlias: dgc_trust_anchor
  cert-auth:
    header-fields:
      thumbprint: X-SSL-Client-SHA256
      distinguished-name: X-SSL-Client-DN
