server:
  port: 8090
spring:
  profiles:
    group:
      "dev": "h2"
  application:
    name: eu-digital-green-certificates-issuence
  datasource:
    jndi-name: jdbc/dgc
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false
    change-log: classpath:db/changelog.xml
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  server:
    port: -1
issuance:
  dgciPrefix: "did:web:authority:dgci:V1:DE:blabla:"
dgc:
  trustAnchor:
    keyStorePath: /ec/prod/app/san/dgc/dgc-ta.jks
    keyStorePass: dgc-p4ssw0rd
    certificateAlias: dgc_trust_anchor
  cert-auth:
    header-fields:
      thumbprint: X-SSL-Client-SHA256
      distinguished-name: X-SSL-Client-DN
springdoc:
  api-docs:
    enabled: false
