name: ci-release-notes
on:
  release:
    types:
    - created
jobs:
  release-notes:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: release-notes
      run: npx github-release-notes release --override --tags ${APP_TAG}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
