name: Sonar Cloud Check
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: s4u/maven-settings-action@v2
        with:
          githubServer: false
          servers: |
            [
              {
                "id": "dgc-github",
                "username": "${{ secrets.GPR_USER }}",
                "password": "${{ secrets.GPR_PAT }}"
              },
              {
                "id": "ehd-github",
                "username": "${{ secrets.GPR_USER }}",
                "password": "${{ secrets.GPR_PAT }}"
              }
            ]
      - name: Sonar Check
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}